# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'presentation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import view.resource.resource

class Ui_WidgetPresentacion(QtWidgets.QWidget):
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.setupUi(self)
        
    def setupUi(self, WidgetPresentacion):
        WidgetPresentacion.setObjectName("WidgetPresentacion")
        WidgetPresentacion.resize(758, 495)
        WidgetPresentacion.setAutoFillBackground(True)
        WidgetPresentacion.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(WidgetPresentacion)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(WidgetPresentacion)
        self.label_4.setMinimumSize(QtCore.QSize(250, 250))
        self.label_4.setMaximumSize(QtCore.QSize(200, 200))
        self.label_4.setAutoFillBackground(True)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/img/logo_UM.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(WidgetPresentacion)
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #1b4e8f;\n"
"font-size:30px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WidgetPresentacion)
        font = QtGui.QFont()
        font.setFamily("Verdana [MS]")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(99, 100, 104);\n"
"font-size:20px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(WidgetPresentacion)
        font = QtGui.QFont()
        font.setFamily("Verdana [MS]")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(99, 100, 104);\n"
"font-size:15px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(WidgetPresentacion)
        QtCore.QMetaObject.connectSlotsByName(WidgetPresentacion)

    def retranslateUi(self, WidgetPresentacion):
        _translate = QtCore.QCoreApplication.translate
        WidgetPresentacion.setWindowTitle(_translate("WidgetPresentacion", "Form"))
        self.label_3.setText(_translate("WidgetPresentacion", "LinReg"))
        self.label.setText(_translate("WidgetPresentacion", "Asistente para el desarrollo de análisis de regresión lineal"))
        self.label_2.setText(_translate("WidgetPresentacion", "Versión: 1.0.0"))

