# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_data_filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDataFilter(object):
    def setupUi(self, WidgetDataFilter):
        WidgetDataFilter.setObjectName("WidgetDataFilter")
        WidgetDataFilter.resize(882, 471)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WidgetDataFilter)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WidgetDataFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableViewDataFrame = QtWidgets.QTableView(WidgetDataFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewDataFrame.sizePolicy().hasHeightForWidth())
        self.tableViewDataFrame.setSizePolicy(sizePolicy)
        self.tableViewDataFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.tableViewDataFrame.setObjectName("tableViewDataFrame")
        self.verticalLayout.addWidget(self.tableViewDataFrame)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(WidgetDataFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listViewVariable = QtWidgets.QListView(WidgetDataFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewVariable.sizePolicy().hasHeightForWidth())
        self.listViewVariable.setSizePolicy(sizePolicy)
        self.listViewVariable.setMinimumSize(QtCore.QSize(250, 0))
        self.listViewVariable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listViewVariable.setObjectName("listViewVariable")
        self.verticalLayout_2.addWidget(self.listViewVariable)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 148, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(WidgetDataFilter)
        QtCore.QMetaObject.connectSlotsByName(WidgetDataFilter)

    def retranslateUi(self, WidgetDataFilter):
        _translate = QtCore.QCoreApplication.translate
        WidgetDataFilter.setWindowTitle(_translate("WidgetDataFilter", "Form"))
        self.label.setText(_translate("WidgetDataFilter", "Datos Iniciales"))
        self.label_2.setText(_translate("WidgetDataFilter", "Selecciones las variables del modelaje"))
