# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_charts_coeff_model_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetChartsCoeffModelSelect(object):
    def setupUi(self, WidgetChartsCoeffModelSelect):
        WidgetChartsCoeffModelSelect.setObjectName("WidgetChartsCoeffModelSelect")
        WidgetChartsCoeffModelSelect.resize(651, 521)
        self.gLayout = QtWidgets.QGridLayout(WidgetChartsCoeffModelSelect)
        self.gLayout.setObjectName("gLayout")
        self.tWidgetChart = QtWidgets.QTableWidget(WidgetChartsCoeffModelSelect)
        self.tWidgetChart.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tWidgetChart.setShowGrid(False)
        self.tWidgetChart.setGridStyle(QtCore.Qt.NoPen)
        self.tWidgetChart.setColumnCount(3)
        self.tWidgetChart.setObjectName("tWidgetChart")
        self.tWidgetChart.setRowCount(0)
        self.tWidgetChart.horizontalHeader().setVisible(False)
        self.tWidgetChart.horizontalHeader().setStretchLastSection(True)
        self.tWidgetChart.verticalHeader().setVisible(False)
        self.tWidgetChart.verticalHeader().setStretchLastSection(True)
        self.gLayout.addWidget(self.tWidgetChart, 0, 0, 1, 1)

        self.retranslateUi(WidgetChartsCoeffModelSelect)
        QtCore.QMetaObject.connectSlotsByName(WidgetChartsCoeffModelSelect)

    def retranslateUi(self, WidgetChartsCoeffModelSelect):
        _translate = QtCore.QCoreApplication.translate
        WidgetChartsCoeffModelSelect.setWindowTitle(_translate("WidgetChartsCoeffModelSelect", "Form"))
