# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_analys_multi_colinualidad.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetAnalysMultiColinualidad(object):
    def setupUi(self, WidgetAnalysMultiColinualidad):
        WidgetAnalysMultiColinualidad.setObjectName("WidgetAnalysMultiColinualidad")
        WidgetAnalysMultiColinualidad.resize(701, 504)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WidgetAnalysMultiColinualidad)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableViewMultiColinealidad = QtWidgets.QTableView(WidgetAnalysMultiColinualidad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewMultiColinealidad.sizePolicy().hasHeightForWidth())
        self.tableViewMultiColinealidad.setSizePolicy(sizePolicy)
        self.tableViewMultiColinealidad.setMaximumSize(QtCore.QSize(16777215, 54))
        self.tableViewMultiColinealidad.setObjectName("tableViewMultiColinealidad")
        self.verticalLayout.addWidget(self.tableViewMultiColinealidad)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(WidgetAnalysMultiColinualidad)
        QtCore.QMetaObject.connectSlotsByName(WidgetAnalysMultiColinualidad)

    def retranslateUi(self, WidgetAnalysMultiColinualidad):
        _translate = QtCore.QCoreApplication.translate
        WidgetAnalysMultiColinualidad.setWindowTitle(_translate("WidgetAnalysMultiColinualidad", "Form"))
