# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_others_charts_model_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetOthersChartsModelSelect(object):
    def setupUi(self, WidgetOthersChartsModelSelect):
        WidgetOthersChartsModelSelect.setObjectName("WidgetOthersChartsModelSelect")
        WidgetOthersChartsModelSelect.resize(400, 300)
        self.gLayout = QtWidgets.QGridLayout(WidgetOthersChartsModelSelect)
        self.gLayout.setObjectName("gLayout")

        self.retranslateUi(WidgetOthersChartsModelSelect)
        QtCore.QMetaObject.connectSlotsByName(WidgetOthersChartsModelSelect)

    def retranslateUi(self, WidgetOthersChartsModelSelect):
        _translate = QtCore.QCoreApplication.translate
        WidgetOthersChartsModelSelect.setWindowTitle(_translate("WidgetOthersChartsModelSelect", "Form"))
