# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_others_charts_model_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetOthersChartsModelSelect(object):
    def setupUi(self, WidgetOthersChartsModelSelect):
        WidgetOthersChartsModelSelect.setObjectName("WidgetOthersChartsModelSelect")
        WidgetOthersChartsModelSelect.resize(667, 545)
        self.gLayout = QtWidgets.QGridLayout(WidgetOthersChartsModelSelect)
        self.gLayout.setObjectName("gLayout")
        self.tWidgetCharts = QtWidgets.QTableWidget(WidgetOthersChartsModelSelect)
        self.tWidgetCharts.setShowGrid(False)
        self.tWidgetCharts.setGridStyle(QtCore.Qt.NoPen)
        self.tWidgetCharts.setColumnCount(3)
        self.tWidgetCharts.setObjectName("tWidgetCharts")
        self.tWidgetCharts.setRowCount(0)
        self.tWidgetCharts.horizontalHeader().setVisible(False)
        self.tWidgetCharts.horizontalHeader().setStretchLastSection(True)
        self.tWidgetCharts.verticalHeader().setVisible(False)
        self.tWidgetCharts.verticalHeader().setStretchLastSection(True)
        self.gLayout.addWidget(self.tWidgetCharts, 0, 0, 1, 1)

        self.retranslateUi(WidgetOthersChartsModelSelect)
        QtCore.QMetaObject.connectSlotsByName(WidgetOthersChartsModelSelect)

    def retranslateUi(self, WidgetOthersChartsModelSelect):
        _translate = QtCore.QCoreApplication.translate
        WidgetOthersChartsModelSelect.setWindowTitle(_translate("WidgetOthersChartsModelSelect", "Form"))
