# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_test_independence_residual.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetTestIndependenceResidual(object):
    def setupUi(self, WidgetTestIndependenceResidual):
        WidgetTestIndependenceResidual.setObjectName("WidgetTestIndependenceResidual")
        WidgetTestIndependenceResidual.resize(664, 177)
        self.gridLayout = QtWidgets.QGridLayout(WidgetTestIndependenceResidual)
        self.gridLayout.setObjectName("gridLayout")
        self.labelDURBIN_WATSON = QtWidgets.QLabel(WidgetTestIndependenceResidual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDURBIN_WATSON.sizePolicy().hasHeightForWidth())
        self.labelDURBIN_WATSON.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDURBIN_WATSON.setFont(font)
        self.labelDURBIN_WATSON.setObjectName("labelDURBIN_WATSON")
        self.gridLayout.addWidget(self.labelDURBIN_WATSON, 0, 0, 1, 1)
        self.lODURBIN_WATSON = QtWidgets.QLabel(WidgetTestIndependenceResidual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lODURBIN_WATSON.sizePolicy().hasHeightForWidth())
        self.lODURBIN_WATSON.setSizePolicy(sizePolicy)
        self.lODURBIN_WATSON.setObjectName("lODURBIN_WATSON")
        self.gridLayout.addWidget(self.lODURBIN_WATSON, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(404, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 3)
        self.labelBREUSH_GGODFREY = QtWidgets.QLabel(WidgetTestIndependenceResidual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBREUSH_GGODFREY.sizePolicy().hasHeightForWidth())
        self.labelBREUSH_GGODFREY.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelBREUSH_GGODFREY.setFont(font)
        self.labelBREUSH_GGODFREY.setObjectName("labelBREUSH_GGODFREY")
        self.gridLayout.addWidget(self.labelBREUSH_GGODFREY, 1, 0, 1, 1)
        self.lOBREUSH_GGODFREY = QtWidgets.QLabel(WidgetTestIndependenceResidual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lOBREUSH_GGODFREY.sizePolicy().hasHeightForWidth())
        self.lOBREUSH_GGODFREY.setSizePolicy(sizePolicy)
        self.lOBREUSH_GGODFREY.setObjectName("lOBREUSH_GGODFREY")
        self.gridLayout.addWidget(self.lOBREUSH_GGODFREY, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(316, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.labelBREUSH_GGODFREY_PVALUE = QtWidgets.QLabel(WidgetTestIndependenceResidual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBREUSH_GGODFREY_PVALUE.sizePolicy().hasHeightForWidth())
        self.labelBREUSH_GGODFREY_PVALUE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelBREUSH_GGODFREY_PVALUE.setFont(font)
        self.labelBREUSH_GGODFREY_PVALUE.setObjectName("labelBREUSH_GGODFREY_PVALUE")
        self.gridLayout.addWidget(self.labelBREUSH_GGODFREY_PVALUE, 1, 3, 1, 1)
        self.lOBREUSH_GGODFREY_PVALUE = QtWidgets.QLabel(WidgetTestIndependenceResidual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lOBREUSH_GGODFREY_PVALUE.sizePolicy().hasHeightForWidth())
        self.lOBREUSH_GGODFREY_PVALUE.setSizePolicy(sizePolicy)
        self.lOBREUSH_GGODFREY_PVALUE.setObjectName("lOBREUSH_GGODFREY_PVALUE")
        self.gridLayout.addWidget(self.lOBREUSH_GGODFREY_PVALUE, 1, 4, 1, 1)

        self.retranslateUi(WidgetTestIndependenceResidual)
        QtCore.QMetaObject.connectSlotsByName(WidgetTestIndependenceResidual)

    def retranslateUi(self, WidgetTestIndependenceResidual):
        _translate = QtCore.QCoreApplication.translate
        WidgetTestIndependenceResidual.setWindowTitle(_translate("WidgetTestIndependenceResidual", "Form"))
        self.labelDURBIN_WATSON.setText(_translate("WidgetTestIndependenceResidual", "Prueba de Durbin-Watson:"))
        self.lODURBIN_WATSON.setText(_translate("WidgetTestIndependenceResidual", "NA"))
        self.labelBREUSH_GGODFREY.setText(_translate("WidgetTestIndependenceResidual", "Prueba de Breush-Godfrey:"))
        self.lOBREUSH_GGODFREY.setText(_translate("WidgetTestIndependenceResidual", "NA"))
        self.labelBREUSH_GGODFREY_PVALUE.setText(_translate("WidgetTestIndependenceResidual", "P-valor:"))
        self.lOBREUSH_GGODFREY_PVALUE.setText(_translate("WidgetTestIndependenceResidual", "NA"))
