# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_charts_coeff_model_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetChartsCoeffModelSelect(object):
    def setupUi(self, WidgetChartsCoeffModelSelect):
        WidgetChartsCoeffModelSelect.setObjectName("WidgetChartsCoeffModelSelect")
        WidgetChartsCoeffModelSelect.resize(651, 521)
        self.gLayout = QtWidgets.QGridLayout(WidgetChartsCoeffModelSelect)
        self.gLayout.setObjectName("gLayout")

        self.retranslateUi(WidgetChartsCoeffModelSelect)
        QtCore.QMetaObject.connectSlotsByName(WidgetChartsCoeffModelSelect)

    def retranslateUi(self, WidgetChartsCoeffModelSelect):
        _translate = QtCore.QCoreApplication.translate
        WidgetChartsCoeffModelSelect.setWindowTitle(_translate("WidgetChartsCoeffModelSelect", "Form"))
