# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_details_model_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDetailsModelSelect(object):
    def setupUi(self, WidgetDetailsModelSelect):
        WidgetDetailsModelSelect.setObjectName("WidgetDetailsModelSelect")
        WidgetDetailsModelSelect.resize(941, 521)
        self.gridLayout = QtWidgets.QGridLayout(WidgetDetailsModelSelect)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidgetDetailsModelSelect = QtWidgets.QTabWidget(WidgetDetailsModelSelect)
        self.tabWidgetDetailsModelSelect.setObjectName("tabWidgetDetailsModelSelect")
        self.tabTestNormalResidual = QtWidgets.QWidget()
        self.tabTestNormalResidual.setObjectName("tabTestNormalResidual")
        self.tabWidgetDetailsModelSelect.addTab(self.tabTestNormalResidual, "")
        self.tabTestNormalResidualNot = QtWidgets.QWidget()
        self.tabTestNormalResidualNot.setObjectName("tabTestNormalResidualNot")
        self.tabWidgetDetailsModelSelect.addTab(self.tabTestNormalResidualNot, "")
        self.tabChartNormalResidualNot = QtWidgets.QWidget()
        self.tabChartNormalResidualNot.setObjectName("tabChartNormalResidualNot")
        self.tabWidgetDetailsModelSelect.addTab(self.tabChartNormalResidualNot, "")
        self.tabChartNormalResidual = QtWidgets.QWidget()
        self.tabChartNormalResidual.setObjectName("tabChartNormalResidual")
        self.tabWidgetDetailsModelSelect.addTab(self.tabChartNormalResidual, "")
        self.gridLayout.addWidget(self.tabWidgetDetailsModelSelect, 0, 0, 1, 1)

        self.retranslateUi(WidgetDetailsModelSelect)
        self.tabWidgetDetailsModelSelect.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WidgetDetailsModelSelect)

    def retranslateUi(self, WidgetDetailsModelSelect):
        _translate = QtCore.QCoreApplication.translate
        WidgetDetailsModelSelect.setWindowTitle(_translate("WidgetDetailsModelSelect", "Form"))
        self.tabWidgetDetailsModelSelect.setTabText(self.tabWidgetDetailsModelSelect.indexOf(self.tabTestNormalResidual), _translate("WidgetDetailsModelSelect", "Prueba de normalidad (Residuales no escalados)"))
        self.tabWidgetDetailsModelSelect.setTabText(self.tabWidgetDetailsModelSelect.indexOf(self.tabTestNormalResidualNot), _translate("WidgetDetailsModelSelect", "Pruebas de normalidad (Residuales estudertizados"))
        self.tabWidgetDetailsModelSelect.setTabText(self.tabWidgetDetailsModelSelect.indexOf(self.tabChartNormalResidualNot), _translate("WidgetDetailsModelSelect", "Gráficos de normalidad residuales no escalados"))
        self.tabWidgetDetailsModelSelect.setTabText(self.tabWidgetDetailsModelSelect.indexOf(self.tabChartNormalResidual), _translate("WidgetDetailsModelSelect", "Graficos de normalidad residuales estudertizados"))
